### ISSUE TITLE
Write Issues Request Specs

### ISSUE THREAD

**Issue by CyberStrike** [Code-for-Miami/lobbster#14]
Remove and replace generated issue specs.

## Description

Replace tests covered in `Issues Controller Spec` and `Issues Routing Spec` with corresponding tests in the Request Spec. See our [Contributing guidelines](https://github.com/Code-for-Miami/lobbster/blob/master/CONTRIBUTING.md) for direction on how testing works in the project.

## Context

We are only doing unit tests on Model and integration tests with Request Specs

## Tasks

- [x] Create `Issues Request Spec`
- [ ] Remove `Issues Controller Spec`
- [ ] Remove `Issues Routing Spec`
