### ISSUE TITLE
Add Tests for User Model

### ISSUE THREAD

**Issue by CyberStrike** [Code-for-Miami/lobbster#15]
## Tasks

- [ ] Remove Controller and Spec
- [ ] Remove Route and Spec
- [ ] Create User Factory
- [ ] Create User Model Test

## Context

Bringing project in line with guidelines
